vich_uploader:
    db_driver: orm

    mappings:
        trade_image:
            uri_prefix: '%trade_images%'
            upload_destination: '%kernel.project_dir%/public/%trade_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
